import ReduxProvider from "./ReduxProvider";
import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Mini-Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Navbar />
          {children}
          <footer style={{ textAlign: "center", padding: "20px", background: "#eee", marginTop: "20px" }}>
            <p>&copy; 2025 Mini-Project. All rights reserved.</p>
          </footer>
        </ReduxProvider>
      </body>
    </html>
  );
}
